# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "win10box"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  
  # use this to install chocolatey via powershell:
  #config.vm.provision "shell", inline: <<-SHELL
  #  iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
  #SHELL
  
  config.vm.provision "shell", path: "provision.cmd"
  config.vm.provision :windows_reboot
  
end
